Loading private profiles properly
dimdenGD/OldTwitter pull request #148
Opened 2023-07-04 14:46 UTC by 0xWerz

## Preview:

![image](https://github.com/dimdenGD/OldTwitter/assets/78509039/f8b89004-73b3-447d-9954-9d071f09ca5a)

## Inspired from the 2015 UI:
![image](https://github.com/dimdenGD/OldTwitter/assets/78509039/f3e5b0ab-b1b6-4f0f-96f2-564a6392888e)

2023-07-04 14:53 UTC, dimdenGD requested changes
Does this support being followed to protected user? You should be allowed to see tweets if you are

2023-07-04 14:53 UTC, dimdenGD commented on layouts/profile/script.js
> +    document.getElementById('tweet-nav').hidden = pageUser.statuskes_count === 0 || user_protected || !(subpage === 'profile' || subpage === 'replies' || subpage === 'media');
Typo

2023-07-04 14:53 UTC, dimdenGD commented on layouts/profile/script.js
> +                ).innerHTML = `<div style="padding: 50px;color: var(--darker-gray);"><h1> Tweets are protected </h1> <p> This account's Tweets are protected. Only confirmed followers have access to @
Needs to use locale files instead of text in code

2023-07-04 15:48 UTC, 0xWerz commented on layouts/profile/script.js
> +                ).innerHTML = `<div style="padding: 50px;color: var(--darker-gray);"><h1> Tweets are protected </h1> <p> This account's Tweets are protected. Only confirmed followers have access to @
Should be good now.

2023-07-04 15:52 UTC, dimdenGD commented
This doesn't follow proper format of locale files. Every line can only have `message`, `description` and `example` fields (in this case it's just `message` with multiple different lines.  Also you shouldn't use Google Translate or whatever tool you used, only add English and if you know any other language you can translate it yourself.

2023-07-06 06:44 UTC, 0xWerz commented
I think the description field is necessary; there are two blocks of text, the title and the bottom description, which are different in font and size. What do you think?

2023-07-06 09:39 UTC, dimdenGD commented
"Description" field is used to help translators give context, not to be used in code itself. Just make another line for text you have inside "description" and put it inside "message". Also please move new lines to the bottom of locale file so it can be easily seen as new thing to translate.

2023-07-06 10:54 UTC, 0xWerz commented
I have simply replicated what you've done with the `hasnt_tweeted` field.

```js
document.getElementById('no-tweets').innerHTML = `
          <h3>${LOC.hasnt_tweeted.message.replace('$SCREEN_NAME$', `<span>${pageUser.screen_name}</span>`)}</h3>
          <p>${LOC.when_theyll_tweet.message}</p>
        `;
```

```json

"hasnt_tweeted": { "message": "@$SCREEN_NAME$ hasn't tweeted", "placeholders": { "screen_name": { "content": "loading" } } },
"when_theyll_tweet": { "message": "When they do, their Tweets will show up here." },
```

2023-07-06 14:53 UTC, merged

2023-07-06 14:53 UTC, dimdenGD commented
Thank you!